---
- name: Install packagae expect
  apt: name=expect state=present

- name: install init pkg From Ubuntu
  apt:
    name: '{{ item }}'
  when: ansible_distribution == "Ubuntu"
  register: utpkg_result
  with_items:
    - "gcc"
    - "g++"
    - "libstdc++5"
    - "libaio1"
    - "libaio-dev"

- name: Copy install shell
  copy: src=install.sh dest=/{{ user }}/automation/portal_web/ owner={{ user }} mode=0755

- name: Execute shell
  shell: /{{ user }}/automation/portal_web/install.sh

