DROP TABLE "ACTIONINFO";
DROP TABLE "AUTOSCALEEVENTINFO";
DROP TABLE "AUTOSCALEINFO";
DROP TABLE "DBINFO";
DROP TABLE "FILESTORAGEINFO";
DROP TABLE "FILESTORAGEMAPPING";
DROP TABLE "GROUPEXECUTEINFO";
DROP TABLE "GROUPINFO";
DROP TABLE "HOSTSHAREINSTANCEMAPPINGINFO";
DROP TABLE "IMAGE";
DROP TABLE "IMAGELAYERMAPPED";
DROP TABLE "IMAGESTATEINFO";
DROP TABLE "INNERFILESYSTEMINFO";
DROP TABLE "INSTANCESPECINFO";
DROP TABLE "NODEIMAGE";
DROP TABLE "PACKINFO";
DROP TABLE "PUBLICIPINFO";
DROP TABLE "SERVICEINFO";
DROP TABLE "STORAGEGROUPINFO";
DROP TABLE "STORAGESERVERGROUPINFO";
DROP TABLE "STORAGESERVERINFO";
DROP TABLE "STORAGEUNITINFO";
DROP TABLE "VPORTINFO";
DROP TABLE "VSWITCHINFO";
DROP TABLE "LAYER";
DROP TABLE "PHYSICALIMAGE";
DROP TABLE "INSTANCEINFO";
DROP TABLE "SUBNETINFO";
DROP TABLE "NETWORKINFO";
DROP TABLE "HOSTINFO";
DROP TABLE "AGGREGATESTATSENTRY";
DROP TABLE "CSVM_FILE_DIV";
DROP TABLE "CSVM_FILE_STALE";
DROP TABLE "CSVM_FILE";
DROP TABLE "CSVM_DB";
DROP TABLE "CSVM_SSVR";
DROP TABLE "CSVM_SSVR_GROUP";
DROP TABLE "CSVM_STORAGE";
DROP TABLE "CSVM_STORAGE_GROUP";
DROP TABLE "DNSRECORDINFO";
DROP TABLE "DNSZONEINFO";
DROP TABLE "FLOWENTRY";
DROP TABLE "FLOWSTATSENTRY";
DROP TABLE "GATEWAYINFO";
DROP TABLE "GROUPENTRY";
DROP TABLE "LINKENTRY";
DROP TABLE "PORTENTRY";
DROP TABLE "PORTSTATSENTRY";
DROP TABLE "SWITCHENTRY";
DROP TABLE "WEBCONSOLEINFO";

CREATE TABLE "ACTIONINFO" (
	"ACTIONID" NUMBER(15),
	"GROUPID" NUMBER(15),
	"ACTIONTYPE" NUMBER(1),
	"CONTENTTYPE" VARCHAR(25),
	"CONTENT" VARCHAR(1000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "AGGREGATESTATSENTRY" (
	"ID" NUMBER(25),
	"BYTE_COUNT" NUMBER(25),
	"FLOW_COUNT" NUMBER(25),
	"PACKET_COUNT" NUMBER(25),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"DELTA_BYTE_COUNT" NUMBER(25),
	"DELTA_PACKET_COUNT" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "AUTOSCALEEVENTINFO" (
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"AUTOSCALEID" NUMBER,
	"EVENTTYPE" NUMBER,
	"EVENTTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "AUTOSCALEINFO" (
	"AUTOSCALEID" NUMBER,
	"MIN" NUMBER,
	"MAX" NUMBER,
	"OUTEVENTID" NUMBER,
	"OUTPOLICY" VARCHAR(255),
	"OUTCOOLDOWN" NUMBER,
	"INEVENTID" NUMBER,
	"INPOLICY" VARCHAR(255),
	"INCOOLDOWN" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"RECENTINEVENT" TIMESTAMP,
	"RECENTOUTEVENT" TIMESTAMP,
	"EVENTHANDLING" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;





CREATE TABLE "CSVM_DB" (
	"DB_UUID" VARCHAR(8),
	"SSVR_GROUP_UUID" VARCHAR(8)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_FILE" (
	"FILE_ID" NUMBER,
	"FILE_NAME" VARCHAR(256),
	"FILE_SIZE" NUMBER,
	"DB_UUID" VARCHAR(8),
	"STRIPING_SIZE" NUMBER,
	"DIV_COUNT" NUMBER,
	"REDUN_COUNT" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_FILE_DIV" (
	"FILE_ID" NUMBER,
	"DIV_NUM" NUMBER,
	"REDUN_NUM" NUMBER,
	"FILE_DIV_SIZE" NUMBER,
	"SSVR_ID" NUMBER,
	"FILE_DIV_PATH" VARCHAR(256)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_FILE_STALE" (
	"FILE_ID" NUMBER,
	"REDUN_NUM" NUMBER,
	"STRIPENO" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_SSVR" (
	"SSVR_ID" NUMBER,
	"SSVR_UUID" VARCHAR(8),
	"STORAGE_ID" NUMBER,
	"STORAGE_UUID" VARCHAR(8),
	"TENANT_IP" VARCHAR(40),
	"TENANT_PORT" NUMBER,
	"SSVR_GROUP_UUID" VARCHAR(8),
	"INVALID_FLAG" NUMBER(1)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_SSVR_GROUP" (
	"SSVR_GROUP_UUID" VARCHAR(8),
	"STORAGE_GROUP_UUID" VARCHAR(8)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_STORAGE" (
	"STORAGE_ID" NUMBER,
	"STORAGE_UUID" VARCHAR(8),
	"STORAGE_TYPE" NUMBER,
	"TOTAL_SIZE" NUMBER,
	"STORAGE_GROUP_UUID" VARCHAR(8)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CSVM_STORAGE_GROUP" (
	"STORAGE_GROUP_UUID" VARCHAR(8)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "DBINFO" (
	"DBID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"DBINSTANCEID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"PROJECTID" NUMBER,
	"INSTALLFLAG" NUMBER,
	"STORAGETYPE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "DNSRECORDINFO" (
	"RECORDID" NUMBER(15),
	"RECORDUUID" VARCHAR(64),
	"ZONEID" NUMBER(15),
	"DATATYPE" VARCHAR(10),
	"TTL" NUMBER(12),
	"HOST" VARCHAR(64),
	"DATA" VARCHAR(1000),
	"CREATETIME" TIMESTAMP,
	"UPDATETIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "DNSZONEINFO" (
	"ZONEID" NUMBER(15),
	"ZONEUUID" VARCHAR(64),
	"TENANTID" NUMBER(15),
	"DOMAINNAME" VARCHAR(256),
	"DESCRIPTION" VARCHAR(256),
	"CREATETIME" TIMESTAMP,
	"UPDATETIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FILESTORAGEINFO" (
	"FILESTORAGEID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER(9),
	"FREESIZE" NUMBER(9),
	"ISRW" NUMBER(1),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CDSLOGINUSERID" VARCHAR(255),
	"CDSLOGINUSERPW" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"METADATA" VARCHAR(2048)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FILESTORAGEMAPPING" (
	"INSTANCEID" NUMBER,
	"FILESTORAGEID" NUMBER,
	"INSTANCEMOUNTPATH" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FLOWENTRY" (
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(25),
	"HARD_TIMEOUT" NUMBER(25),
	"IDLE_TIMEOUT" NUMBER(25),
	"INSTRUCTION" VARCHAR(1000),
	"MATCH" VARCHAR(1000),
	"OUT_GROUP" NUMBER(10),
	"OUT_PORT" NUMBER(10),
	"PRIORITY" NUMBER(10),
	"STATE" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FLOWSTATSENTRY" (
	"ID" NUMBER(25),
	"BYTE_COUNT" NUMBER(25),
	"DURATION_NSEC" NUMBER(25),
	"DURATION_SEC" NUMBER(25),
	"FLAGS" NUMBER(5),
	"HARD_TIMEOUT" NUMBER(25),
	"IDLE_TIMEOUT" NUMBER(25),
	"PACKET_COUNT" NUMBER(25),
	"PRIORITY" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(25),
	"DPID" NUMBER(25),
	"DELTA_BYTE_COUNT" NUMBER(25),
	"DELTA_PACKET_COUNT" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "GATEWAYINFO" (
	"GATEWAY_ID" NUMBER(25),
	"IPV4_ADDR" VARCHAR(100),
	"MAC_ADDR" VARCHAR(100),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "GROUPENTRY" (
	"GROUP_ID" NUMBER(10),
	"BUCKETS" VARCHAR(1000),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "GROUPEXECUTEINFO" (
	"GROUPID" NUMBER(15),
	"SVCORDER" NUMBER(5),
	"SVCNAME" VARCHAR(100),
	"SVCUUID" VARCHAR(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "GROUPINFO" (
	"GROUPID" NUMBER(19),
	"CREATEDTIME" TIMESTAMP,
	"GROUPDESCRIPTION" VARCHAR(255),
	"GROUPNAME" VARCHAR(255),
	"GROUPTAGS" VARCHAR(255),
	"PROJECTUUID" NUMBER(19),
	"SCRIPT" VARCHAR(10000),
	"STATUS" VARCHAR(255),
	"TENANTUUID" NUMBER(19),
	"UPDATEDTIME" TIMESTAMP,
	"CREATOR" VARCHAR(255),
	"INSTANCECOUNT" NUMBER(10),
	"PACKNAME" VARCHAR(255),
	"PROJECTID" NUMBER(19),
	"TENANTID" NUMBER(19)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "HOSTINFO" (
	"HOSTID" NUMBER,
	"HOSTNAME" VARCHAR(255),
	"HOSTTYPE" VARCHAR(255),
	"HYPERVISORTYPE" VARCHAR(255),
	"HOSTIP" VARCHAR(255),
	"CPUARCH" VARCHAR(255),
	"TOTALCPU" NUMBER,
	"TOTALMEMORY" NUMBER,
	"TOTALDISK" NUMBER,
	"POOLEDDISK" NUMBER,
	"AVAILABILITYZONE" VARCHAR(255),
	"STATUS" VARCHAR(255),
	"HOSTPMAC" VARCHAR(255),
	"FRONTENDPORT" VARCHAR(255),
	"BACKENDPORT" VARCHAR(255),
	"MANAGEMENTPORT" VARCHAR(255),
	"SWITCHDPID" NUMBER,
	"SWITCHPORT" NUMBER,
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DESCRIPTION" VARCHAR(255),
	"META" VARCHAR(2048),
	"ACTIVE" NUMBER(1),
	"NODETYPE" NUMBER,
	"COMPUTETOTALCPU" NUMBER,
	"COMPUTEFREECPU" NUMBER,
	"COMPUTETOTALMEMORY" NUMBER,
	"COMPUTEFREEMEMORY" NUMBER,
	"STORAGETOTALCPU" NUMBER,
	"STORAGETOTALMEMORY" NUMBER,
	"STORAGETOTALSIZE" NUMBER,
	"STORAGEFREESIZE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;



CREATE TABLE "HOSTSHAREINSTANCEMAPPINGINFO" (
	"HOSTSHAREINSTANCEMAPPINGID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"HOSTPATH" VARCHAR(255),
	"HOSTSHAREINSTANCEMAPPINGUUID" VARCHAR(255),
	"INSTANCEID" NUMBER(19),
	"INSTANCEPATH" VARCHAR(255),
	"INSTANCEUUID" VARCHAR(255),
	"UPDATEDTIME" TIMESTAMP,
	"ZFS" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMAGE" (
	"TENANTID" NUMBER(15),
	"TENANTUUID" VARCHAR(32),
	"PROJECTID" NUMBER(15),
	"PROJECTUUID" VARCHAR(32),
	"UPLOADERUUID" VARCHAR(32),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"IMAGETAG" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"DESCRIPTION" VARCHAR(1024),
	"SHARED" VARCHAR(15),
	"STATE" VARCHAR(5),
	"UPLOADEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"UPDATERUUID" VARCHAR(32),
	"UPLOADERID" NUMBER(15),
	"UPDATERID" NUMBER(15),
	"PRODUCTNAME" VARCHAR(1024),
	"PRODUCTVERSION" VARCHAR(1024),
	"ISSNAPSHOT" VARCHAR(2),
	"IMAGEFROM" VARCHAR(32),
	"TENANTNAME" VARCHAR(1024),
	"PROJECTNAME" VARCHAR(1024),
	"UPLOADERNAME" VARCHAR(1024),
	"UPDATERNAME" VARCHAR(1024)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMAGELAYERMAPPED" (
	"IMAGEID" NUMBER(15),
	"LAYERID" VARCHAR(64),
	"LAYERORDER" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMAGESTATEINFO" (
	"IMAGEID" NUMBER(15),
	"TENANTID" NUMBER(15),
	"STATEFLAG" NUMBER(2)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"ROOTPATHNAME" VARCHAR(255),
	"TOTALSIZE" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "INSTANCEINFO" (
	"INSTANCEID" NUMBER,
	"INSTANCEUUID" VARCHAR(255),
	"TENANTID" NUMBER,
	"TENANTUUID" VARCHAR(255),
	"PROJECTID" NUMBER,
	"PROJECTUUID" VARCHAR(255),
	"CREATOR" VARCHAR(255),
	"INSTANCENAME" VARCHAR(255),
	"INSTANCEDESCRIPTION" VARCHAR(255),
	"INSTANCETAGS" VARCHAR(255),
	"INSTANCETYPE" VARCHAR(255),
	"ENV" VARCHAR(4095),
	"METADATA" VARCHAR(4095),
	"IMAGEID" NUMBER,
	"IMAGEUUID" VARCHAR(255),
	"HYPERVISORTYPE" VARCHAR(255),
	"SPECID" NUMBER,
	"SPECUUID" VARCHAR(255),
	"CPUS" NUMBER,
	"MEMORY" NUMBER,
	"INSTANCESTATUS" VARCHAR(255),
	"RESULT" VARCHAR(255),
	"RESULTMESSAGE" VARCHAR(600),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"AUTOSCALEID" NUMBER,
	"AUTOSCALEUUID" VARCHAR(255),
	"STORAGEGROUPID" NUMBER,
	"STORAGEGROUPUUID" VARCHAR(255),
	"STORAGETYPE" NUMBER,
	"INSTANCEGROUPID" NUMBER,
	"BACKENDIP" VARCHAR(255),
	"FRONTENDIP" VARCHAR(255),
	"PUBLICIPID" NUMBER,
	"PUBLICIPUUID" VARCHAR(255),
	"INSTANCEGROUPUUID" VARCHAR(255),
	"ISCDS" NUMBER,
	"AUTOCOUNT" NUMBER,
	"ISDB" NUMBER,
	"ISSERVER" NUMBER,
	"ISSYSTEM" NUMBER,
	"ACTIONID" NUMBER,
	"HOSTID" NUMBER,
	"INSTANCEPMAC" VARCHAR(255),
	"ISLB" NUMBER,
	"EVENTSTATUS" VARCHAR(255),
	"DBID" NUMBER,
	"DBMETADATA" VARCHAR(4096),
	"USBCOPYENABLE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "INSTANCESPECINFO" (
	"SPECID" NUMBER(15),
	"SPECUUID" VARCHAR(25),
	"SPECTYPE" VARCHAR(255),
	"SPECCPU" NUMBER(2),
	"SPECMEMORY" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "LAYER" (
	"LAYERID" VARCHAR(64),
	"REFCNT" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "LINKENTRY" (
	"SRC_DPID" NUMBER(25),
	"DST_DPID" NUMBER(25),
	"DST_PORT" NUMBER(10),
	"SRC_PORT" NUMBER(10),
	"COST" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "NETWORKINFO" (
	"NETWORKID" NUMBER,
	"VLANID" NUMBER(5),
	"TENANTID" NUMBER,
	"NETWORKUUID" VARCHAR(255),
	"NAME" VARCHAR(40),
	"TYPE" NUMBER(1),
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(20) DEFAULT 'Active'
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "NODEIMAGE" (
	"NODEIP" VARCHAR(15),
	"IMAGEID" NUMBER(15),
	"REFCNT" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PACKINFO" (
	"PACKAGEID" NUMBER,
	"PACKAGEUUID" VARCHAR(255),
	"PACKAGEDESC" VARCHAR(255),
	"PACKAGEINFO" VARCHAR(2000),
	"PACKAGENAME" VARCHAR(255),
	"PACKAGESOURCE" VARCHAR(10000),
	"PACKAGEUSER" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PHYSICALIMAGE" (
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"PRODUCTNAME" VARCHAR(255),
	"PRODUCTVERSION" VARCHAR(255),
	"IMAGECMD" VARCHAR(1024),
	"IMAGEENV" VARCHAR(4096),
	"IMAGEFROM" VARCHAR(255),
	"SUPPORTOS" VARCHAR(255),
	"DEFAULTCHECK" VARCHAR(2),
	"INSTALLEDPROGRAMS" VARCHAR(4096),
	"ISSNAPSHOT" VARCHAR(2),
	"IMPORTEDTIME" TIMESTAMP,
	"EDITEDTIME" TIMESTAMP,
	"IMAGECLASSIFICATION" VARCHAR(1024)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTENTRY" (
	"PORT_NO" NUMBER(10),
	"ADVERTISED" NUMBER(10),
	"CONFIG" NUMBER(10),
	"CURR" NUMBER(10),
	"CURR_SPEED" NUMBER(10),
	"HW_ADDR" BLOB,
	"MAX_SPEED" NUMBER(10),
	"NAME" VARCHAR(255),
	"PEER" NUMBER(10),
	"STATE" NUMBER(10),
	"SUPPORTED" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTSTATSENTRY" (
	"ID" NUMBER(25),
	"COLLISIONS" NUMBER(25),
	"DURATION_NSEC" NUMBER(25),
	"DURATION_SEC" NUMBER(25),
	"RX_BYTES" NUMBER(25),
	"RX_CRC_ERR" NUMBER(25),
	"RX_DROPPED" NUMBER(25),
	"RX_ERRORS" NUMBER(25),
	"RX_FRAME_ERR" NUMBER(25),
	"RX_OVER_ERR" NUMBER(25),
	"RX_PACKETS" NUMBER(25),
	"TX_BYTES" NUMBER(25),
	"TX_DROPPED" NUMBER(25),
	"TX_ERRORS" NUMBER(25),
	"TX_PACKETS" NUMBER(25),
	"UPDATED_TIME" TIMESTAMP,
	"PORT_NO" NUMBER(10),
	"DPID" NUMBER(25),
	"DELTA_TX_BYTES" NUMBER(25),
	"DELTA_TX_PACKETS" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PUBLICIPINFO" (
	"PUBLICIP" VARCHAR(20),
	"PUBLICIPID" NUMBER,
	"PUBLICIPUUID" VARCHAR(255),
	"VPORTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(45) DEFAULT 'Active'
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "SERVICEINFO" (
	"SVCID" NUMBER,
	"SVCCREATENAME" VARCHAR(255),
	"SVCDELETENAME" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "STORAGEGROUPINFO" (
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"TOTALSTORAGENUMBER" NUMBER,
	"USAGE" VARCHAR(255),
	"STORAGETYPE" NUMBER,
	"FREESIZE" NUMBER,
	"TENANTID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TENANTID" NUMBER,
	"SSVRTYPE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"PRIVATEPATHNAME" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "STORAGESERVERINFO" (
	"STORAGESERVERID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGESERVERIP" VARCHAR(255),
	"STORAGESERVERPORT" NUMBER,
	"INSTANCEID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "STORAGEUNITINFO" (
	"STORAGEUNITID" NUMBER,
	"STORAGENODEID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"STORAGETYPE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "SUBNETINFO" (
	"SUBNETID" NUMBER,
	"NETWORKID" NUMBER,
	"SUBNETUUID" VARCHAR(255),
	"IPADDR" VARCHAR(255),
	"NETMASK" VARCHAR(45),
	"CIDR" NUMBER(3),
	"GATEWAY" VARCHAR(45),
	"DNS" VARCHAR(45),
	"VLANID" NUMBER(5),
	"NAME" VARCHAR(40),
	"TYPE" NUMBER(1),
	"ISLB" NUMBER(1),
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(20) DEFAULT 'Active'
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "SWITCHENTRY" (
	"DPID" NUMBER(25),
	"AUXILIARY_ID" NUMBER(10),
	"CAPABILITIES" NUMBER(10),
	"DP_DESC" VARCHAR(255),
	"HW_DESC" VARCHAR(255),
	"MFR_DESC" VARCHAR(255),
	"ACTION_MODE" NUMBER(10),
	"N_BUFFERS" NUMBER(10),
	"N_TABLES" NUMBER(10),
	"SERIAL_NUM" VARCHAR(255),
	"SW_DESC" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP,
	"TYPE" NUMBER(10),
	"IS_ACTIVE" NUMBER(1) DEFAULT 0,
	"IS_CORE" NUMBER(1) DEFAULT 0,
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "VPORTINFO" (
	"VPORTID" NUMBER,
	"MAC1" VARCHAR(45),
	"MAC2" NUMBER(5),
	"IPVALUE" NUMBER(13),
	"VLANID" NUMBER(5),
	"NETWORKID" NUMBER,
	"IPADDR" VARCHAR(30),
	"MACADDR" VARCHAR(30),
	"SUBNETID" NUMBER,
	"VPORTUUID" VARCHAR(255),
	"NAME" VARCHAR(40),
	"STATUS" VARCHAR(45) DEFAULT 'Active',
	"NETWORKTYPE" VARCHAR(50),
	"INSTANCEID" NUMBER DEFAULT -1,
	"TARGETPOOLID" NUMBER DEFAULT -1,
	"CREATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "VSWITCHINFO" (
	"VLANID" NUMBER(5),
	"HOSTID" NUMBER,
	"NAME" VARCHAR(100),
	"PORTNAME" VARCHAR(100)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "WEBCONSOLEINFO" (
	"INSTANCEID" NUMBER(12),
	"SOCATPID" NUMBER(12),
	"WEBSOCKETPID" NUMBER(12),
	"SOCATPORT" NUMBER(12),
	"WEBSOCKETPORT" NUMBER(12),
	"CREATETIME" TIMESTAMP,
	"ACCESSTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;



CREATE INDEX "AGGREGATE_INDEX" ON "AGGREGATESTATSENTRY" (
	"ID" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_DB_PK" ON "CSVM_DB" (
	"DB_UUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_FILE_DIV_PK" ON "CSVM_FILE_DIV" (
	"FILE_ID" ASC,
	"DIV_NUM" ASC,
	"REDUN_NUM" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_FILE_PK" ON "CSVM_FILE" (
	"FILE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_FILE_STALE_PK" ON "CSVM_FILE_STALE" (
	"FILE_ID" ASC,
	"REDUN_NUM" ASC,
	"STRIPENO" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_FILE_UQ" ON "CSVM_FILE" (
	"DB_UUID" ASC,
	"FILE_NAME" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_SSVR_GROUP_PK" ON "CSVM_SSVR_GROUP" (
	"SSVR_GROUP_UUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_SSVR_PK" ON "CSVM_SSVR" (
	"SSVR_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_STORAGE_GROUP_PK" ON "CSVM_STORAGE_GROUP" (
	"STORAGE_GROUP_UUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CSVM_STORAGE_PK" ON "CSVM_STORAGE" (
	"STORAGE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE INDEX "FLOWSTATS_INDEX" ON "FLOWSTATSENTRY" (
	"ID" ASC,
	"DPID" ASC,
	"TABLE_NO" ASC,
	"COOKIE" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "HOST_PRIM" ON "HOSTINFO" (
	"HOSTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMAGELAYERMAPPED_COMPLEX_PK" ON "IMAGELAYERMAPPED" (
	"IMAGEID" ASC,
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMAGE_COMPLEX_PK" ON "IMAGE" (
	"TENANTID" ASC,
	"PROJECTID" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON100200831" ON "VSWITCHINFO" (
	"VLANID" ASC,
	"HOSTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON77100123" ON "FILESTORAGEINFO" (
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON92200033" ON "LAYER" (
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON94100472" ON "NETWORKINFO" (
	"NETWORKID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON94200868" ON "NETWORKINFO" (
	"NETWORKUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON95400368" ON "SUBNETINFO" (
	"SUBNETID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON95500850" ON "SUBNETINFO" (
	"SUBNETUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON96900636" ON "INSTANCEINFO" (
	"INSTANCEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON98200899" ON "VPORTINFO" (
	"VPORTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON98300172" ON "VPORTINFO" (
	"VPORTUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON99200547" ON "PUBLICIPINFO" (
	"PUBLICIPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN_CON99300211" ON "PUBLICIPINFO" (
	"PUBLICIPUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "NODEIMAGE_COMPLEX_PK" ON "NODEIMAGE" (
	"NODEIP" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_DBINFO" ON "DBINFO" (
	"DBID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_FILESTORAGEMAPPING" ON "FILESTORAGEMAPPING" (
	"INSTANCEID" ASC,
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_INNERFILESYSTEMINFO" ON "INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_PI" ON "PHYSICALIMAGE" (
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_RECORDINFO" ON "DNSRECORDINFO" (
	"RECORDID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_SERVICEINFO" ON "SERVICEINFO" (
	"SVCID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_STORAGEGROUPINFO" ON "STORAGEGROUPINFO" (
	"STORAGEGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_STORAGESERVERGROUPINFO" ON "STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_STORAGESERVERINFO" ON "STORAGESERVERINFO" (
	"STORAGESERVERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "PK_ZONEINFO" ON "DNSZONEINFO" (
	"ZONEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE INDEX "PORTSTATS_INDEX" ON "PORTSTATSENTRY" (
	"ID" ASC,
	"DPID" ASC,
	"PORT_NO" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_AGGREGATESTATSENTRY" ON "AGGREGATESTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_FLOWENTRY" ON "FLOWENTRY" (
	"TABLE_NO" ASC,
	"COOKIE" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_FLOWSTATSENTRY" ON "FLOWSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_GATEWAYINFO" ON "GATEWAYINFO" (
	"GATEWAY_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_GROUPENTRY" ON "GROUPENTRY" (
	"GROUP_ID" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_LINKENTRY" ON "LINKENTRY" (
	"SRC_DPID" ASC,
	"DST_DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_PORTENTRY" ON "PORTENTRY" (
	"PORT_NO" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_PORTSTATSENTRY" ON "PORTSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_SWITCHENTRY" ON "SWITCHENTRY" (
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_NetworkInfo" ON "NETWORKINFO" (
	"VLANID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_NetworkInfo2" ON "NETWORKINFO" (
	"NETWORKID" ASC,
	"VLANID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_PublicIpInfo" ON "PUBLICIPINFO" (
	"PUBLICIP" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_PublicIpInfo2" ON "PUBLICIPINFO" (
	"VPORTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_SubnetInfo" ON "SUBNETINFO" (
	"SUBNETID" ASC,
	"VLANID" ASC,
	"NETWORKID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_SubnetInfo2" ON "SUBNETINFO" (
	"NETWORKID" ASC,
	"IPADDR" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_VPortInfo" ON "VPORTINFO" (
	"MAC1" ASC,
	"MAC2" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_VPortInfo2" ON "VPORTINFO" (
	"SUBNETID" ASC,
	"IPVALUE" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "uq_VPortInfo3" ON "VPORTINFO" (
	"SUBNETID" ASC,
	"IPADDR" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "CSVM_DB" ADD CONSTRAINT "CSVM_DB_PK"
PRIMARY KEY (
	"DB_UUID"
);

ALTER TABLE "CSVM_FILE_DIV" ADD CONSTRAINT "CSVM_FILE_DIV_PK"
PRIMARY KEY (
	"FILE_ID",
	"DIV_NUM",
	"REDUN_NUM"
);

ALTER TABLE "CSVM_FILE" ADD CONSTRAINT "CSVM_FILE_PK"
PRIMARY KEY (
	"FILE_ID"
);

ALTER TABLE "CSVM_FILE_STALE" ADD CONSTRAINT "CSVM_FILE_STALE_PK"
PRIMARY KEY (
	"FILE_ID",
	"REDUN_NUM",
	"STRIPENO"
);

ALTER TABLE "CSVM_FILE" ADD CONSTRAINT "CSVM_FILE_UQ"
UNIQUE (
	"DB_UUID",
	"FILE_NAME"
);

ALTER TABLE "CSVM_SSVR_GROUP" ADD CONSTRAINT "CSVM_SSVR_GROUP_PK"
PRIMARY KEY (
	"SSVR_GROUP_UUID"
);

ALTER TABLE "CSVM_SSVR" ADD CONSTRAINT "CSVM_SSVR_PK"
PRIMARY KEY (
	"SSVR_ID"
);

ALTER TABLE "CSVM_STORAGE_GROUP" ADD CONSTRAINT "CSVM_STORAGE_GROUP_PK"
PRIMARY KEY (
	"STORAGE_GROUP_UUID"
);

ALTER TABLE "CSVM_STORAGE" ADD CONSTRAINT "CSVM_STORAGE_PK"
PRIMARY KEY (
	"STORAGE_ID"
);

ALTER TABLE "IMAGELAYERMAPPED" ADD CONSTRAINT "IMAGELAYERMAPPED_COMPLEX_PK"
PRIMARY KEY (
	"IMAGEID",
	"LAYERID"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "IMAGE_COMPLEX_PK"
PRIMARY KEY (
	"TENANTID",
	"PROJECTID",
	"IMAGEID"
);

ALTER TABLE "INSTANCEINFO" ADD 
PRIMARY KEY (
	"INSTANCEID"
);

ALTER TABLE "VPORTINFO" MODIFY 	"VPORTID" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"MAC1" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"MAC2" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"IPVALUE" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"IPADDR" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"MACADDR" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"SUBNETID" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"VPORTUUID" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "VPORTINFO" MODIFY 	"NETWORKTYPE" NOT NULL;

ALTER TABLE "VPORTINFO" ADD 
PRIMARY KEY (
	"VPORTID"
);

ALTER TABLE "VPORTINFO" ADD 
UNIQUE (
	"VPORTUUID"
);

ALTER TABLE "PUBLICIPINFO" MODIFY 	"PUBLICIP" NOT NULL;

ALTER TABLE "PUBLICIPINFO" MODIFY 	"PUBLICIPID" NOT NULL;

ALTER TABLE "PUBLICIPINFO" MODIFY 	"PUBLICIPUUID" NOT NULL;

ALTER TABLE "PUBLICIPINFO" ADD 
PRIMARY KEY (
	"PUBLICIPID"
);

ALTER TABLE "PUBLICIPINFO" ADD 
UNIQUE (
	"PUBLICIPUUID"
);

ALTER TABLE "HOSTINFO" ADD 
PRIMARY KEY (
	"HOSTID"
);

ALTER TABLE "VSWITCHINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "VSWITCHINFO" MODIFY 	"HOSTID" NOT NULL;

ALTER TABLE "SWITCHENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "SWITCHENTRY" ADD 
PRIMARY KEY (
	"DPID"
);

ALTER TABLE "PORTENTRY" MODIFY 	"PORT_NO" NOT NULL;

ALTER TABLE "PORTENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "PORTENTRY" ADD 
PRIMARY KEY (
	"PORT_NO",
	"DPID"
);

ALTER TABLE "LINKENTRY" MODIFY 	"SRC_DPID" NOT NULL;

ALTER TABLE "LINKENTRY" MODIFY 	"DST_DPID" NOT NULL;

ALTER TABLE "LINKENTRY" ADD 
PRIMARY KEY (
	"SRC_DPID",
	"DST_DPID"
);

ALTER TABLE "FLOWENTRY" MODIFY 	"TABLE_NO" NOT NULL;

ALTER TABLE "FLOWENTRY" MODIFY 	"COOKIE" NOT NULL;

ALTER TABLE "FLOWENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "FLOWENTRY" ADD 
PRIMARY KEY (
	"TABLE_NO",
	"COOKIE",
	"DPID"
);

ALTER TABLE "GROUPENTRY" MODIFY 	"GROUP_ID" NOT NULL;

ALTER TABLE "GROUPENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "GROUPENTRY" ADD 
PRIMARY KEY (
	"GROUP_ID",
	"DPID"
);

ALTER TABLE "AGGREGATESTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "AGGREGATESTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "FLOWSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "FLOWSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "PORTSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "PORTSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "IMAGE" MODIFY 	"TENANTUUID" NOT NULL;

ALTER TABLE "IMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "IMAGE" MODIFY 	"IMAGENAME" NOT NULL;

ALTER TABLE "IMAGE" MODIFY 	"STATE" NOT NULL;

ALTER TABLE "PHYSICALIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "PHYSICALIMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "PHYSICALIMAGE" MODIFY 	"PRODUCTNAME" NOT NULL;

ALTER TABLE "PHYSICALIMAGE" MODIFY 	"PRODUCTVERSION" NOT NULL;

ALTER TABLE "GATEWAYINFO" MODIFY 	"GATEWAY_ID" NOT NULL;

ALTER TABLE "GATEWAYINFO" ADD 
PRIMARY KEY (
	"GATEWAY_ID"
);

ALTER TABLE "DNSZONEINFO" MODIFY 	"ZONEID" NOT NULL;

ALTER TABLE "DNSZONEINFO" MODIFY 	"DOMAINNAME" NOT NULL;

ALTER TABLE "DNSRECORDINFO" MODIFY 	"RECORDID" NOT NULL;

ALTER TABLE "DNSRECORDINFO" MODIFY 	"DATATYPE" NOT NULL;

ALTER TABLE "DNSRECORDINFO" MODIFY 	"TTL" NOT NULL;

ALTER TABLE "DNSRECORDINFO" MODIFY 	"DATA" NOT NULL;

ALTER TABLE "VSWITCHINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "VSWITCHINFO" MODIFY 	"PORTNAME" NOT NULL;

ALTER TABLE "VSWITCHINFO" ADD 
PRIMARY KEY (
	"VLANID",
	"HOSTID"
);


ALTER TABLE "IMAGESTATEINFO" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMAGESTATEINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMAGESTATEINFO" MODIFY 	"STATEFLAG" NOT NULL;

ALTER TABLE "FILESTORAGEINFO" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "FILESTORAGEINFO" ADD 
PRIMARY KEY (
	"FILESTORAGEID"
);

ALTER TABLE "FILESTORAGEMAPPING" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "FILESTORAGEMAPPING" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "INNERFILESYSTEMINFO" MODIFY 	"INNERFILESYSTEMID" NOT NULL;

ALTER TABLE "INNERFILESYSTEMINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "INNERFILESYSTEMINFO" MODIFY 	"ROOTPATHNAME" NOT NULL;

ALTER TABLE "DBINFO" MODIFY 	"DBID" NOT NULL;

ALTER TABLE "DBINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "DBINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "STORAGEGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "STORAGEGROUPINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "STORAGEGROUPINFO" MODIFY 	"TOTALSTORAGENUMBER" NOT NULL;

ALTER TABLE "STORAGEGROUPINFO" MODIFY 	"USAGE" NOT NULL;

ALTER TABLE "STORAGESERVERGROUPINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "STORAGESERVERGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "STORAGESERVERGROUPINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "STORAGESERVERINFO" MODIFY 	"STORAGESERVERID" NOT NULL;

ALTER TABLE "STORAGESERVERINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "STORAGESERVERINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "STORAGESERVERINFO" MODIFY 	"STORAGESERVERIP" NOT NULL;

ALTER TABLE "STORAGESERVERINFO" MODIFY 	"STORAGESERVERPORT" NOT NULL;

ALTER TABLE "STORAGEUNITINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "STORAGEUNITINFO" MODIFY 	"STORAGENODEID" NOT NULL;

ALTER TABLE "STORAGEUNITINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "STORAGEUNITINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMAGE" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "LAYER" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "LAYER" ADD 
PRIMARY KEY (
	"LAYERID"
);

ALTER TABLE "LAYER" MODIFY 	"REFCNT" NOT NULL;

ALTER TABLE "IMAGELAYERMAPPED" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMAGELAYERMAPPED" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "NODEIMAGE" MODIFY 	"NODEIP" NOT NULL;

ALTER TABLE "NODEIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "NODEIMAGE" MODIFY 	"REFCNT" NOT NULL;

ALTER TABLE "NETWORKINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "NETWORKINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "NETWORKINFO" MODIFY 	"NETWORKUUID" NOT NULL;

ALTER TABLE "NETWORKINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "NETWORKINFO" MODIFY 	"TYPE" NOT NULL;

ALTER TABLE "NETWORKINFO" ADD 
PRIMARY KEY (
	"NETWORKID"
);

ALTER TABLE "NETWORKINFO" ADD 
UNIQUE (
	"NETWORKUUID"
);

ALTER TABLE "SUBNETINFO" MODIFY 	"SUBNETID" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"SUBNETUUID" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"IPADDR" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"NETMASK" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"CIDR" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "SUBNETINFO" MODIFY 	"TYPE" NOT NULL;

ALTER TABLE "SUBNETINFO" ADD 
PRIMARY KEY (
	"SUBNETID"
);

ALTER TABLE "SUBNETINFO" ADD 
UNIQUE (
	"SUBNETUUID"
);

ALTER TABLE "NODEIMAGE" ADD CONSTRAINT "NODEIMAGE_COMPLEX_PK"
PRIMARY KEY (
	"NODEIP",
	"IMAGEID"
);

ALTER TABLE "DBINFO" ADD CONSTRAINT "PK_DBINFO"
PRIMARY KEY (
	"DBID"
);

ALTER TABLE "FILESTORAGEMAPPING" ADD CONSTRAINT "PK_FILESTORAGEMAPPING"
PRIMARY KEY (
	"INSTANCEID",
	"FILESTORAGEID"
);

ALTER TABLE "INNERFILESYSTEMINFO" ADD CONSTRAINT "PK_INNERFILESYSTEMINFO"
PRIMARY KEY (
	"INNERFILESYSTEMID"
);

ALTER TABLE "PHYSICALIMAGE" ADD CONSTRAINT "PK_PI"
PRIMARY KEY (
	"IMAGEID"
);

ALTER TABLE "DNSRECORDINFO" ADD CONSTRAINT "PK_RECORDINFO"
PRIMARY KEY (
	"RECORDID"
);

ALTER TABLE "STORAGEGROUPINFO" ADD CONSTRAINT "PK_STORAGEGROUPINFO"
PRIMARY KEY (
	"STORAGEGROUPID"
);

ALTER TABLE "STORAGESERVERGROUPINFO" ADD CONSTRAINT "PK_STORAGESERVERGROUPINFO"
PRIMARY KEY (
	"STORAGESERVERGROUPID"
);

ALTER TABLE "STORAGESERVERINFO" ADD CONSTRAINT "PK_STORAGESERVERINFO"
PRIMARY KEY (
	"STORAGESERVERID"
);

ALTER TABLE "DNSZONEINFO" ADD CONSTRAINT "PK_ZONEINFO"
PRIMARY KEY (
	"ZONEID"
);

ALTER TABLE "NETWORKINFO" ADD CONSTRAINT "uq_NetworkInfo"
UNIQUE (
	"VLANID"
);

ALTER TABLE "NETWORKINFO" ADD CONSTRAINT "uq_NetworkInfo2"
UNIQUE (
	"NETWORKID",
	"VLANID"
);

ALTER TABLE "PUBLICIPINFO" ADD CONSTRAINT "uq_PublicIpInfo"
UNIQUE (
	"PUBLICIP"
);

ALTER TABLE "PUBLICIPINFO" ADD CONSTRAINT "uq_PublicIpInfo2"
UNIQUE (
	"VPORTID"
);

ALTER TABLE "SUBNETINFO" ADD CONSTRAINT "uq_SubnetInfo"
UNIQUE (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
);

ALTER TABLE "SUBNETINFO" ADD CONSTRAINT "uq_SubnetInfo2"
UNIQUE (
	"NETWORKID",
	"IPADDR"
);

ALTER TABLE "VPORTINFO" ADD CONSTRAINT "uq_VPortInfo"
UNIQUE (
	"MAC1",
	"MAC2"
);

ALTER TABLE "VPORTINFO" ADD CONSTRAINT "uq_VPortInfo2"
UNIQUE (
	"SUBNETID",
	"IPVALUE"
);

ALTER TABLE "VPORTINFO" ADD CONSTRAINT "uq_VPortInfo3"
UNIQUE (
	"SUBNETID",
	"IPADDR"
);

ALTER TABLE "CSVM_DB" ADD CONSTRAINT "CSVM_DB_FK"
FOREIGN KEY (
	"SSVR_GROUP_UUID"
) REFERENCES "CSVM_SSVR_GROUP" (
	"SSVR_GROUP_UUID"
);

ALTER TABLE "CSVM_FILE_DIV" ADD CONSTRAINT "CSVM_FILE_DIV_FK"
FOREIGN KEY (
	"FILE_ID"
) REFERENCES "CSVM_FILE" (
	"FILE_ID"
);

ALTER TABLE "CSVM_FILE_DIV" ADD CONSTRAINT "CSVM_FILE_DIV_SSVR_FK"
FOREIGN KEY (
	"SSVR_ID"
) REFERENCES "CSVM_SSVR" (
	"SSVR_ID"
);

ALTER TABLE "CSVM_FILE" ADD CONSTRAINT "CSVM_FILE_FK"
FOREIGN KEY (
	"DB_UUID"
) REFERENCES "CSVM_DB" (
	"DB_UUID"
);

ALTER TABLE "CSVM_FILE_STALE" ADD CONSTRAINT "CSVM_FILE_STALE_FK"
FOREIGN KEY (
	"FILE_ID"
) REFERENCES "CSVM_FILE" (
	"FILE_ID"
);

ALTER TABLE "CSVM_SSVR" ADD CONSTRAINT "CSVM_SSVR_FK"
FOREIGN KEY (
	"SSVR_GROUP_UUID"
) REFERENCES "CSVM_SSVR_GROUP" (
	"SSVR_GROUP_UUID"
);

ALTER TABLE "CSVM_SSVR_GROUP" ADD CONSTRAINT "CSVM_SSVR_GROUP_FK"
FOREIGN KEY (
	"STORAGE_GROUP_UUID"
) REFERENCES "CSVM_STORAGE_GROUP" (
	"STORAGE_GROUP_UUID"
);

ALTER TABLE "CSVM_SSVR" ADD CONSTRAINT "CSVM_SSVR_STORAGE_FK"
FOREIGN KEY (
	"STORAGE_ID"
) REFERENCES "CSVM_STORAGE" (
	"STORAGE_ID"
);

ALTER TABLE "CSVM_STORAGE" ADD CONSTRAINT "CSVM_STORAGE_FK"
FOREIGN KEY (
	"STORAGE_GROUP_UUID"
) REFERENCES "CSVM_STORAGE_GROUP" (
	"STORAGE_GROUP_UUID"
);

ALTER TABLE "IMAGELAYERMAPPED" ADD CONSTRAINT "FK2_PI"
FOREIGN KEY (
	"IMAGEID"
) REFERENCES "PHYSICALIMAGE" (
	"IMAGEID"
);

ALTER TABLE "NODEIMAGE" ADD CONSTRAINT "FK3_PI"
FOREIGN KEY (
	"IMAGEID"
) REFERENCES "PHYSICALIMAGE" (
	"IMAGEID"
);

ALTER TABLE "FLOWENTRY" ADD CONSTRAINT "FK_FLOWENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "GROUPENTRY" ADD CONSTRAINT "FK_GROUPENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "IMAGELAYERMAPPED" ADD CONSTRAINT "FK_LAYER_ID"
FOREIGN KEY (
	"LAYERID"
) REFERENCES "LAYER" (
	"LAYERID"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "FK_PI"
FOREIGN KEY (
	"IMAGEID"
) REFERENCES "PHYSICALIMAGE" (
	"IMAGEID"
);

ALTER TABLE "PORTENTRY" ADD CONSTRAINT "FK_PORTENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "DNSRECORDINFO" ADD CONSTRAINT "FK_RECORDINFO"
FOREIGN KEY (
	"ZONEID"
) REFERENCES "DNSZONEINFO" (
	"ZONEID"
);

ALTER TABLE "PUBLICIPINFO" ADD CONSTRAINT "fk_PublicIpInfo_PortInfo"
FOREIGN KEY (
	"VPORTID"
) REFERENCES "VPORTINFO" (
	"VPORTID"
);

ALTER TABLE "SUBNETINFO" ADD CONSTRAINT "fk_SubnetInfo_NetworkInfo"
FOREIGN KEY (
	"NETWORKID",
	"VLANID"
) REFERENCES "NETWORKINFO" (
	"NETWORKID",
	"VLANID"
);

ALTER TABLE "VPORTINFO" ADD CONSTRAINT "fk_VPortInfo_InstanceInfo"
FOREIGN KEY (
	"INSTANCEID"
) REFERENCES "INSTANCEINFO" (
	"INSTANCEID"
);

ALTER TABLE "VPORTINFO" ADD CONSTRAINT "fk_VPortInfo_SubnetInfo"
FOREIGN KEY (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
) REFERENCES "SUBNETINFO" (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
);

ALTER TABLE "VSWITCHINFO" ADD CONSTRAINT "fk_VswitchInfo_HostInfo"
FOREIGN KEY (
	"HOSTID"
) REFERENCES "HOSTINFO" (
	"HOSTID"
);

ALTER TABLE "VSWITCHINFO" ADD CONSTRAINT "fk_VswitchInfo_NetworkInfo"
FOREIGN KEY (
	"VLANID"
) REFERENCES "NETWORKINFO" (
	"VLANID"
);

CREATE UNIQUE INDEX "IMPADMIN_CON280500661" ON "AUTOSCALEINFO" (
	"AUTOSCALEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "AUTOSCALEINFO" ADD 
PRIMARY KEY (
	"AUTOSCALEID"
);

COMMIT;
EXIT;
