CREATE TABLE "PORTAL"."HISTORY" (
	"ID" NUMBER,
	"UUID" VARCHAR(255),
	"TARGETTYPE" VARCHAR(255),
	"TARGETID" NUMBER,
	"SUBJECTTYPE" VARCHAR(255),
	"SUBJECTID" NUMBER,
	"SUBJECTNAME" VARCHAR(255),
	"OBJECTTYPE" VARCHAR(255),
	"OBJECTID" NUMBER,
	"OBJECTNAME" VARCHAR(255),
	"CONTENTSTYPE" VARCHAR(255),
	"CONTENTS" VARCHAR(255),
	"TIME" DATE
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PERMISSION" (
	"ID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"UUID" VARCHAR(255),
	"CREATEDTIME" DATE,
	"UPDATEDTIME" DATE,
	"DELETEDTIME" DATE,
	"ISDELETED" CHAR(1),
	"OBJECTTYPE" VARCHAR(255),
	"ACTION" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PROJECT" (
	"ID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DELETEDTIME" TIMESTAMP,
	"ISDELETED" CHAR(1),
	"TENANTID" NUMBER,
	"UUID" VARCHAR(255),
	"SUPERPROJECTID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PROJECT_ROLE" (
	"ID" NUMBER,
	"UUID" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"PROJECTID" NUMBER,
	"createdtime" DATE,
	"updatedtime" DATE,
	"deletedtime" DATE,
	"isdeleted" CHAR(1)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PROJECT_SERVICE" (
	"PROJECTID" NUMBER,
	"SERVICEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PROJECT_USER_RELATION" (
	"PROJECTID" NUMBER,
	"USERID" NUMBER,
	"ROLEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."PROJECT_USER_ROLE_RELATION" (
	"PROJECTUSERID" NUMBER,
	"PROJECTROLEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."ROLE" (
	"ID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" DATE,
	"UPDATEDTIME" DATE,
	"DELETEDTIME" DATE,
	"ISDELETED" CHAR(1),
	"UUID" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."ROLES_RELATION" (
	"GROUPEDROLEID" NUMBER,
	"ROLEID" NUMBER,
	"PROJECTID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."ROLE_PERMISSION_RELATION" (
	"ROLEID" NUMBER,
	"PERMISSIONID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."SERVICE" (
	"ID" NUMBER,
	"UUID" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" DATE,
	"UPDATEDTIME" DATE,
	"DELETEDTIME" DATE,
	"ISDELETED" CHAR(1)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TENANT" (
	"ID" NUMBER,
	"NAME" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DELETEDTIME" TIMESTAMP,
	"DESCRIPTION" VARCHAR(255),
	"ISDELETED" CHAR(1),
	"UUID" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TENANT_ROLE" (
	"ID" NUMBER,
	"UUID" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"TENANTID" NUMBER,
	"CREATEDTIME" DATE,
	"UPDATEDTIME" DATE,
	"DELETEDTIME" DATE,
	"ISDELETED" CHAR(1)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TENANT_SERVICE" (
	"TENANTID" NUMBER,
	"SERVICEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TENANT_USER_RELATION" (
	"TENANTID" NUMBER,
	"USERID" NUMBER,
	"ROLEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TENANT_USER_ROLE_RELATION" (
	"TENANTUSERID" NUMBER,
	"TENANTROLEID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."TEST" (
	"ID" NUMBER,
	"NAME" VARCHAR(255),
	"COST" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTAL"."USERS" (
	"ID" NUMBER,
	"EMAIL" VARCHAR(255),
	"NAME" VARCHAR(255),
	"POSITION" VARCHAR(255),
	"DEPARTMENT" VARCHAR(255),
	"COMPANYID" NUMBER,
	"PHONE" VARCHAR(255),
	"PAYMENTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DELETEDTIME" TIMESTAMP,
	"ISDELETED" CHAR(1),
	"UUID" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

commit;
exit;
