Drop table AGGREGATESTATSENTRY;
Drop table PORTSTATSENTRY;
Drop table FLOWSTATSENTRY;
Drop table FLOWENTRY;
Drop table GROUPENTRY;
Drop table LINKENTRY;
Drop table PORTENTRY;
Drop table SWITCHENTRY;


CREATE TABLE "AGGREGATESTATSENTRY" (
	"ID" NUMBER(25),
	"BYTE_COUNT" NUMBER(25),
	"FLOW_COUNT" NUMBER(25),
	"PACKET_COUNT" NUMBER(25),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"DELTA_BYTE_COUNT" NUMBER(25),
	"DELTA_PACKET_COUNT" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FLOWENTRY" (
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(25),
	"HARD_TIMEOUT" NUMBER(25),
	"IDLE_TIMEOUT" NUMBER(25),
	"INSTRUCTION" VARCHAR(1000),
	"MATCH" VARCHAR(1000),
	"OUT_GROUP" NUMBER(10),
	"OUT_PORT" NUMBER(10),
	"PRIORITY" NUMBER(10),
	"STATE" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "FLOWSTATSENTRY" (
	"ID" NUMBER(25),
	"BYTE_COUNT" NUMBER(25),
	"DURATION_NSEC" NUMBER(25),
	"DURATION_SEC" NUMBER(25),
	"FLAGS" NUMBER(5),
	"HARD_TIMEOUT" NUMBER(25),
	"IDLE_TIMEOUT" NUMBER(25),
	"PACKET_COUNT" NUMBER(25),
	"PRIORITY" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(25),
	"DPID" NUMBER(25),
	"DELTA_BYTE_COUNT" NUMBER(25),
	"DELTA_PACKET_COUNT" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "GROUPENTRY" (
	"GROUP_ID" NUMBER(10),
	"BUCKETS" VARCHAR(1000),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "LINKENTRY" (
	"SRC_DPID" NUMBER(25),
	"DST_DPID" NUMBER(25),
	"DST_PORT" NUMBER(10),
	"SRC_PORT" NUMBER(10),
	"COST" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTENTRY" (
	"PORT_NO" NUMBER(10),
	"ADVERTISED" NUMBER(10),
	"CONFIG" NUMBER(10),
	"CURR" NUMBER(10),
	"CURR_SPEED" NUMBER(10),
	"HW_ADDR" BLOB,
	"MAX_SPEED" NUMBER(10),
	"NAME" VARCHAR(255),
	"PEER" NUMBER(10),
	"STATE" NUMBER(10),
	"SUPPORTED" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "PORTSTATSENTRY" (
	"ID" NUMBER(25),
	"COLLISIONS" NUMBER(25),
	"DURATION_NSEC" NUMBER(25),
	"DURATION_SEC" NUMBER(25),
	"RX_BYTES" NUMBER(25),
	"RX_CRC_ERR" NUMBER(25),
	"RX_DROPPED" NUMBER(25),
	"RX_ERRORS" NUMBER(25),
	"RX_FRAME_ERR" NUMBER(25),
	"RX_OVER_ERR" NUMBER(25),
	"RX_PACKETS" NUMBER(25),
	"TX_BYTES" NUMBER(25),
	"TX_DROPPED" NUMBER(25),
	"TX_ERRORS" NUMBER(25),
	"TX_PACKETS" NUMBER(25),
	"UPDATED_TIME" TIMESTAMP,
	"PORT_NO" NUMBER(10),
	"DPID" NUMBER(25),
	"DELTA_TX_BYTES" NUMBER(25),
	"DELTA_TX_PACKETS" NUMBER(25)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "SWITCHENTRY" (
	"DPID" NUMBER(25),
	"AUXILIARY_ID" NUMBER(10),
	"CAPABILITIES" NUMBER(10),
	"DP_DESC" VARCHAR(255),
	"HW_DESC" VARCHAR(255),
	"MFR_DESC" VARCHAR(255),
	"ACTION_MODE" NUMBER(10),
	"N_BUFFERS" NUMBER(10),
	"N_TABLES" NUMBER(10),
	"SERIAL_NUM" VARCHAR(255),
	"SW_DESC" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP,
	"TYPE" NUMBER(10),
	"IS_ACTIVE" NUMBER(1) DEFAULT 0,
	"IS_CORE" NUMBER(1) DEFAULT 0
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_SWITCHENTRY" ON "SWITCHENTRY" (
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_PORTENTRY" ON "PORTENTRY" (
	"PORT_NO" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_GROUPENTRY" ON "GROUPENTRY" (
	"GROUP_ID" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_LINKENTRY" ON "LINKENTRY" (
	"SRC_DPID" ASC,
	"DST_DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_AGGREGATESTATSENTRY" ON "AGGREGATESTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_PORTSTATSENTRY" ON "PORTSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_FLOWENTRY" ON "FLOWENTRY" (
	"TABLE_NO" ASC,
	"COOKIE" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "UNIQUE_FLOWSTATSENTRY" ON "FLOWSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "SWITCHENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "SWITCHENTRY" ADD 
PRIMARY KEY (
	"DPID"
);

ALTER TABLE "PORTENTRY" MODIFY 	"PORT_NO" NOT NULL;

ALTER TABLE "PORTENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "PORTENTRY" ADD 
PRIMARY KEY (
	"PORT_NO",
	"DPID"
);

ALTER TABLE "LINKENTRY" MODIFY 	"SRC_DPID" NOT NULL;

ALTER TABLE "LINKENTRY" MODIFY 	"DST_DPID" NOT NULL;

ALTER TABLE "LINKENTRY" ADD 
PRIMARY KEY (
	"SRC_DPID",
	"DST_DPID"
);

ALTER TABLE "FLOWENTRY" MODIFY 	"TABLE_NO" NOT NULL;

ALTER TABLE "FLOWENTRY" MODIFY 	"COOKIE" NOT NULL;

ALTER TABLE "FLOWENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "FLOWENTRY" ADD 
PRIMARY KEY (
	"TABLE_NO",
	"COOKIE",
	"DPID"
);

ALTER TABLE "GROUPENTRY" MODIFY 	"GROUP_ID" NOT NULL;

ALTER TABLE "GROUPENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "GROUPENTRY" ADD 
PRIMARY KEY (
	"GROUP_ID",
	"DPID"
);

ALTER TABLE "AGGREGATESTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "AGGREGATESTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "FLOWSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "FLOWSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "PORTSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "PORTSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "FLOWENTRY" ADD CONSTRAINT "FK_FLOWENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "GROUPENTRY" ADD CONSTRAINT "FK_GROUPENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "PORTENTRY" ADD CONSTRAINT "FK_PORTENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "SWITCHENTRY" (
	"DPID"
);

commit;
exit;
