---
- name: Auth server run
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  environment:
    TIBERO_IP: '{{ t_ip }}'
    TIBERO_PORT: '{{ tport }}'
    TIBERO_USER: '{{ authtid }}'
    TIBERO_PW: '{{ authtpw }}'
    AUTH_SERVER_PORT_1: '{{ auth_server_port_1 }}'
    AUTH_SERVER_PORT_2: '{{ auth_server_port_2 }}'
    AUTH_SERVER_PORT_3: '{{ auth_server_port_3 }}'
    AUTH_IMAGE_NAME: '{{ auth_image_name }}'
    DOMAINNAME: '{{ domain_name }}'
  vars_files:
    - "../vars/external_vars.yml"

  roles:
    - auth_run
