---
- name: Setting bridge setting for I1 model
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  environment:
    SETTING_IP: '{{ SETTING_IP }}'
    SETTING_NETMASK: '{{ SETTING_NETMASK }}'
    SETTING_GATEWAY: '{{ SETTING_GATEWAY }}'
    SETTING_GATEWAY_NET: '{{ SETTING_GATEWAY_NET }}'
    SETTING_INTERFACE: '{{ SETTING_INTERFACE }}'
  vars_files:
    - "../vars/bridge_setting.yml"
  roles:
    - bridge_setting
