---
- name: Init ansible home
  hosts: '{{ hosts }}'
 
- name: Install Tibero6 with manual
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  environment:
    TB_HOME: '{{ tb_home }}'
    TB_SID: '{{ tb_sid }}'
    PATH: "{{ tb_home }}/bin:{{ tb_home }}/client/bin:{{ ansi_path }}"
    LD_LIBRARY_PATH: "{{ tb_home }}/lib:{{ tb_home }}/client/lib"
    TID: '{{ tid }}'
    TPW: '{{ tpw }}'
  vars_files:
    - "../vars/external_vars.yml"
    - "../vars/po7_vars.yml"

  roles:
    - i1dbmanual_install
