---
- name: Init ansible home
  hosts: '{{ hosts }}'
  remote_user: root

- name: Install PO7 manually
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  vars_files:
    - "../vars/po7_vars.yml"
    - "../vars/domain-config.yml"
    - "../vars/osarch_vars.yml"

  environment:
    PATH: "{{ jeus_home }}/bin:{{ jeus_home }}/lib:{{ ansi_path }}"
    PROOBJECT_HOME: "{{ po_home }}"

  roles:
    - pomanual_install
