#!/bin/bash

# init script for compute node with sdn.
# by jungsub_shin

### BEGIN INIT INFO
# Provides:          tca-compute
# Required-Start:	 networking
# Required-Stop:     networking
# Default-Start:	 2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Directories
tca_agent_block_home=/root/tca_agent
tca_agent_mem_home=/tmp/tca_agent

tca_rendezvous_result=$tca_agent_mem_home/rendezvous_result

tca_container_lock=$tca_agent_mem_home/container_lock
tca_container_config=$tca_agent_block_home/container_config
tca_container_log=$tca_agent_block_home/container_log
tca_container_root_dir=$tca_agent_block_home/container_root_dir
tca_container_rw_dir=$tca_agent_block_home/container_rw_dir
tca_container_rw_tar=$tca_agent_block_home/container_rw_tar
tca_container_rw_list=$tca_agent_mem_home/container_rw_list

tca_image_layer_lock=$tca_agent_mem_home/image_layer_lock
tca_image_layer_dir=$tca_agent_block_home/image_layer_dir
tca_image_layer_tar=$tca_agent_block_home/image_layer_tar
tca_image_layer_ref=$tca_agent_block_home/image_layer_ref

tca_network_lock=$tca_agent_mem_home/network_lock
tca_network_ref=$tca_agent_mem_home/network_ref

tca_nfs_lock=$tca_agent_mem_home/nfs_lock
tca_nfs_ref=$tca_agent_mem_home/nfs_ref
tca_nfs_mount=$tca_agent_mem_home/nfs_mount

lxc_home=/var/lib/lxc

# Functions
init_directories () {
	mkdir -p $tca_rendezvous_result

	mkdir -p $tca_container_lock
	mkdir -p $tca_container_config
	mkdir -p $tca_container_log
	mkdir -p $tca_container_root_dir
	mkdir -p $tca_container_rw_dir
	mkdir -p $tca_container_rw_tar
	mkdir -p $tca_container_rw_list

	mkdir -p $tca_image_layer_lock
	mkdir -p $tca_image_layer_dir
	mkdir -p $tca_image_layer_tar
	mkdir -p $tca_image_layer_ref

	mkdir -p $tca_network_lock
	mkdir -p $tca_network_ref

	mkdir -p $tca_nfs_lock
	mkdir -p $tca_nfs_ref
	mkdir -p $tca_nfs_mount
}

init_network () {
	modprobe 8021q
	modprobe br_netfilter
	echo 1 > /proc/sys/net/bridge/bridge-nf-filter-vlan-tagged
	echo 1 > /proc/sys/net/bridge/bridge-nf-call-arptables

	arptables -F
	arptables -P FORWARD DROP
	arptables -I FORWARD -i eno1 ! --src-mac 12:34:56:78:9a:bc -j DROP
}

clean_lxc () {
	rm -rf $lxc_home/*
}

umount_cont_root () {
	# Unmount AUFS
	containers_root=$(ls $tca_container_root_dir)
	for root in $containers_root; do
		umount $cont_root_parent/$root
	done
}

# Run
case "$1" in
  start)
	init_directories
	init_network
	clean_lxc
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop|"")
	umount_cont_root
	;;
  *)
	echo "Usage: tca-agent [start|stop]" >&2
	exit 3
	;;
esac

:
