---
- name: Init ansible home
  hosts: '{{ hosts }}'

- name: Run TCNM
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  vars_files:
    - "../vars/po7_vars.yml"
    - "../vars/tcnm_domain-config.yml"
  environment:
    PATH: "{{ jeus_home }}/bin:{{ jeus_home }}/lib:{{ ansi_path }}"
    PROOBJECT_HOME: "{{ po_home }}"
  roles:
    - tcnm_run
